server:
  port: 10010
spring:
  application:
    name: api-gateway
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
zuul:
  prefix: /api #添加路由前缀
  retryable: true
  routes:
    item-service: /item/**  #将商品服务映射到/item/**
    search-service: /search/**
    user-service: /user/**
    auth-service: /auth/**
    cart-service: /cart/**
    order-service: /order/**
    upload-service:
      path: /upload/**
      service: upload-service
      strip-prefix: false
  sensitive-headers:  #禁止使用的头信息,设置为null,都在set-cookie无效
  add-host-header: true  #携带请求本身的host头信息
hystrix: #配置hystrix的熔断超时时长和
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000 # 熔断超时时长：6000ms
ribbon: #ribbon负载均衡的相关配置
  ConnectTimeout: 1000 # ribbon链接超时时长
  ReadTimeout: 2000 # ribbon读取超时时长
  MaxAutoRetries: 0  # 当前服务重试次数
  MaxAutoRetriesNextServer: 0 # 切换服务重试次数
ly:
  cors:
    allowedOrigins:
      - http://manage.leyou.com
      - http://www.leyou.com
      - http://api.leyou.com
    allowCredentials: true
    allowedMethods:
      - GET
      - POST
      - DELETE
      - PUT
      - OPTIONS
    maxAge: 3600
    allowedHeaders:
      - "*"
    path: "/**"
  jwt:
    publicFilePath: C:\\Users\\Bowen\\Desktop\\leyou_jwt\\rsa.pub # 公钥地址
    cookieName: LY_TOKEN # cookie的名称
  filter:
    allowPaths:
      - /api/auth
      - /api/search
      - /api/user/register
      - /api/user/check
      - /api/user/code
      - /api/item
      - /zuul/api/upload
logging:
  level:
    com.leyou.geteway: debug
